name: 'My Composite Action'
description: 'An example composite action'
inputs:
  name:
    description: 'Name to greet'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.name }}"
      shell: bash
