# .github/workflows/use-greet.yml
name: Use Greet Action

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/greet
        with:
          name: 'Chennai Dev'
